SELECT
    p.NAME AS PRODUCT_NAME,
    SUM(o.QUANTITY * p.UNIT_PRICE) AS REVENUE
FROM DBT.RAW_DATA.ORDERS o
JOIN DBT.RAW_DATA.PRODUCTS p
    ON o.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.NAME
ORDER BY REVENUE DESC